# 配置文件版本
version: 5.1.0

# Icarus 主题变体，可选值为 "default" 或 "cyberpunk"
variant: default

# 网站 logo 的路径或 URL
logo: /img/logo.svg

# 页面元数据配置
head:
  # 网站图标的路径或 URL
  favicon: /img/favicon.svg

  # Web 应用清单配置
  # https://developer.mozilla.org/en-US/docs/Web/Manifest
  manifest:
    # Web 应用名称（默认为网站标题）
    name: 张 晓山
    # 应用在空间不足时显示的短名称
    short_name: 
    # Web 应用的起始地址
    start_url: 
    # 应用的默认主题颜色
    theme_color: 
    # 样式表加载前显示的背景色占位符
    background_color: 
    # 网站的首选显示模式
    display: standalone
    # 不同上下文使用的图标图像
    icons:
      -
        # 图标文件路径
        src: ''
        # 图像尺寸（以空格分隔的字符串）
        sizes: ''
        # 图像的媒体类型提示
        type: 

  # Open Graph 元数据
  # https://hexo.io/docs/helpers.html#open-graph
  open_graph:
    # 页面标题（og:title）（可选，一般留空）
    title: 
    # 页面类型（og:type）（可选，一般留空）
    type: blog
    # 页面 URL（og:url）（可选，一般留空）
    url: 
    # 页面封面图（og:image）（可选，一般留空）
    image: 
    # 网站名称（og:site_name）（可选，一般留空）
    site_name: 
    # 页面作者（article:author）（可选，一般留空）
    author: 
    # 页面描述（og:description）（可选，一般留空）
    description: 
    # Twitter 卡片类型（twitter:card）
    twitter_card: 
    # Twitter 用户 ID（twitter:creator）
    twitter_id: 
    # Twitter 站点（twitter:site）
    twitter_site: 
    # Google+ 个人资料链接（已弃用）
    google_plus: 
    # Facebook 管理员 ID
    fb_admins: 
    # Facebook 应用 ID
    fb_app_id: 

  # 结构化数据配置
  # https://developers.google.com/search/docs/guides/intro-structured-data
  structured_data:
    title: 
    description: 
    url: 
    author: 
    publisher: 
    publisher_logo: 
    image: 

  # 额外的 HTML meta 标签（数组形式）
  meta:
    - ''

  # 网站的 RSS 地址
  rss: 

# 页面顶部导航栏配置
navbar:
  # 导航菜单项
  menu:
    Home: /
    Archives: /archives
    Categories: /categories
    Tags: /tags
    About: /about

  # 显示在导航栏右侧的链接
  links:
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus

# 页面页脚配置
footer:
  # 版权信息
  copyright: © 2019
  # 显示在页脚右侧的链接
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Download on GitHub:
      icon: fab fa-github
      url: https://github.com/ppoffice/hexo-theme-icarus

# 文章相关配置
article:
  # 代码高亮设置
  highlight:
    # 代码高亮主题
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    theme: atom-one-light
    # 显示复制代码按钮
    clipboard: true
    # 代码块默认折叠状态，可为 "", "folded", "unfolded"
    fold: unfolded

  # 是否显示预计阅读时间
  readtime: true

  # 是否显示更新时间；"auto" 表示仅在页面有更新时间且不同于发布时间时显示
  update_time: true

  # 文章许可信息区块
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/

# 搜索插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
  type: insight
  # 是否在搜索结果中包含页面
  index_pages: true

# 评论插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
  type: disqus
  # Disqus 的 shortname
  shortname: ''

# 打赏插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
  - type: afdian
    url: ''
  - type: alipay
    qrcode: ''
  - type: buymeacoffee
    url: ''
  - type: patreon
    url: ''
  - type: paypal
    business: ''
    currency_code: USD
  - type: wechat
    qrcode: ''

# 社交分享插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
  type: sharethis
  # ShareThis 插件脚本地址
  install_url: ''

# 侧边栏配置
# 注意：仅当至少包含一个 widget 时侧边栏才会显示
sidebar:
  left:
    # 页面滚动时是否固定侧边栏
    sticky: false
  right:
    sticky: false

# 侧边栏组件配置
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
  - position: left
    type: profile
    author: 张 晓山
    author_title: 卡拉卡拉一号机
    location: 半人马座
    avatar: img/avatar.jpg
    avatar_rounded: false
    gravatar: 
    follow_link: https://github.com/ppoffice
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/ppoffice
      Facebook:
        icon: fab fa-facebook
        url: https://facebook.com
      Twitter:
        icon: fab fa-twitter
        url: https://twitter.com
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: left
    type: links
    links:
      Hexo: https://hexo.io
      Bulma: https://bulma.io
  - position: left
    type: categories
  - position: left
    type: recent_posts
  - position: left
    type: archives
  - position: left
    type: tags
    order_by: name
    amount: 
    show_count: true
  - position: left
    type: subscribe_email
    description: 
    feedburner_id: ''
  - position: left
    type: adsense
    client_id: ''
    slot_id: ''
  - position: left
    type: followit
    description: 
    action_url: ''
    verification_code: ''

# 插件配置
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
  # 启用页面加载动画
  animejs: true
  # 显示返回顶部按钮
  back_to_top: true
  # 百度统计
  baidu_analytics:
    tracking_id: 
  # 必应站长工具
  bing_webmaster:
    tracking_id: 
  # 不蒜子站点/页面访问统计
  busuanzi: false
  # CNZZ 网站统计
  cnzz:
    id: 
    web_id: 
  # Cookie 使用提示弹窗
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  # 开启 lightGallery 和 Justified Gallery 插件
  gallery: true
  # Google Analytics 配置
  google_analytics:
    tracking_id: 
  # Hotjar 用户反馈插件
  hotjar:
    site_id: 
  # 启用 KaTeX 数学公式排版
  katex: false
  # 启用 MathJax 数学公式排版
  mathjax: false
  # 旧版浏览器提示插件
  outdated_browser: false
  # 启用 PJAX 页面无刷新加载
  pjax: true
  # 页面加载时顶部进度条
  progressbar: true
  # Statcounter 统计插件
  statcounter:
    project: 
    security: 
  # Twitter 转化追踪插件
  twitter_conversion_tracking:
    pixel_id: 

# CDN 提供商设置
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
